### ISSUE TITLE
MDB_MAP_FULL error on Windows with LMDB when deleting libraries 

### ISSUE THREAD

**Issue by TianQingX** [man-group/ArcticDB#439] opened 2023-05-30 04:49 UTC
### Describe the bug

Trying to delete the library but fail

### Steps/Code to Reproduce

```python
ac = Arctic('lmdb:///ArcticDBStore')
ac.delete_library(name = 'AStock')
```

### Expected Results

Delete Successful but fail

### OS, Python Version and ArcticDB Version

Python: 3.8.16 (default, Mar  2 2023, 03:18:16) [MSC v.1916 64 bit (AMD64)]
OS: Windows-10-10.0.19041-SP0
ArcticDB: 1.2.1

### Backend storage used

LMDB

### Additional Context

```
---------------------------------------------------------------------------
InternalException                         Traceback (most recent call last)
Cell In[14], line 1
----> 1 ac.delete_library(name = 'AStock')

File [c:\Users\ps\anaconda3\envs\trade\lib\site-packages\arcticdb\arctic.py:175](file:///C:/Users/ps/anaconda3/envs/trade/lib/site-packages/arcticdb/arctic.py:175), in Arctic.delete_library(self, name)
    173 if not self._library_manager.has_library(name):
    174     return
--> 175 self._library_adapter.delete_library(self[name], self._library_manager.get_library_config(name))
    176 self._library_manager.remove_library_config(name)

File [c:\Users\ps\anaconda3\envs\trade\lib\site-packages\arcticdb\adapters\arctic_library_adapter.py:64](file:///C:/Users/ps/anaconda3/envs/trade/lib/site-packages/arcticdb/adapters/arctic_library_adapter.py:64), in ArcticLibraryAdapter.delete_library(self, library, library_config)
     63 def delete_library(self, library: Library, library_config: LibraryConfig):
---> 64     return library._nvs.version_store.clear()

InternalException: (mdb_txn_commit: MDB_MAP_FULL: Environment mapsize limit reached)
```

**Comment by jjerphan** [comment] 2023-05-30 08:01
Hi @TianQingX, thank you for reporting this bug. Can you provide a minimal reproducible example, please?

**Comment by jjerphan** [comment] 2023-05-30 12:11
Closing since this is a duplicate of #229.

**Closed by jjerphan** 2023-05-30 12:11 UTC
Labels: bug
