### ISSUE TITLE
Allow for a secondary index

### ISSUE THREAD

**Issue by reggied** [man-group/ArcticDB#196] opened 2023-04-03 17:43 UTC
This is an enhancement request related to storing a DataFrame with a multi-index. We'd like to use the non-datetime index column as a secondary Arctic index to enhance performance when retrieving data based on that column.

**Comment by mehertz** [comment] 2023-04-04 10:05
This is resolved by #118

**Comment by mehertz** [comment] 2023-04-04 10:05
Duplicate of #118

**Closed by mehertz** 2023-04-04 10:05 UTC
Labels: enhancement
