### ISSUE TITLE
Bring column-slicing back to the segments after defragmentation

### ISSUE THREAD

**Issue by phoebusm** [man-group/ArcticDB#325] opened 2023-05-03 17:16 UTC
API `defragment_symbol_data`, introduced by below ticket, will remove any column slicing present on the data in the new version created. 
[Link](https://github.com/man-group/ArcticDB/issues/33)
This will bring performance down if the symbol has more than 127 columns (default setting of `columns_per_segment`).

Suggestion:
Replacing the usage of `Aggregator` with `pipeline` for better performance

**Comment by alexowens90** [comment] 2024-05-30 10:38
Duplicate of https://github.com/man-group/ArcticDB/issues/729

**Closed by alexowens90** 2024-05-30 10:38 UTC
Labels: enhancement
