### ISSUE TITLE
Support a start date in head and an end date in tail

### ISSUE THREAD

**Issue by zstbsqx** [man-group/ArcticDB#1449] opened 2024-03-21 02:01 UTC
I have a dataframe with DateTimeIndex. All data are saved in a single version, so I can not use `as_of`.

Now I want to get the last record before some timestamp, is it possible? I believe the underlying data structure supports such needs, but `library.tail` method doesn't have a `date_range` option.

**Comment by poodlewars** [comment] 2024-04-07 17:04
Hi @zstbsqx sorry that we haven't replied sooner.

We don't currently have APIs to do this, but I agree it would be a good feature, we'll add this to our backlog.

The closest we have at the moment is the open ended date range read:

```
lib.read("sym", date_range=(None, datetime(2023, 12, 25))).data
```

and then taking the `tail` in Pandas.

**Comment by zstbsqx** [comment] 2024-04-08 07:41
Hi @poodlewars. Thanks for adding this to the backlog.

I agree with your API design about the `end_date` part, but `start_date` argument might be unnecessary. Putting `start_date` in `head()` method sounds more reasonable.

**Comment by zstbsqx** [comment] 2024-04-08 07:42
> Hi @poodlewars. Thanks for adding this to the backlog.
> 
> I agree with your API design about the `end_date` part, but `start_date` argument might be unnecessary. Putting `start_date` in `head()` method sounds more reasonable.

Yes just like the PR title says!

**Comment by poodlewars** [comment] 2024-04-16 14:45
Thanks, there was a typo in my code snippet. I've fixed it now.

**Comment by poodlewars** [comment] 2024-04-18 10:11
This is actually a duplicate of #245 so I'm going to close this issue in favour of that one.

**Closed by poodlewars** 2024-04-18 10:11 UTC
Labels: enhancement
