### ISSUE TITLE
malloc(): unaligned tcache chunk detected

### ISSUE THREAD

**Issue by Tianxu-Jia** [man-group/ArcticDB#277] opened 2023-04-25 15:07 UTC
using lmdb to build a library, then verything is fine. After add new elements using lib.append(name, new_data, metadata={'index': 'aaa'}). Then read the library again, it will show "malloc(): unaligned tcache chunk detected" after several iterm are read.

Whats wrong with it? Can anyboday give me a help?

Many thanks

**Comment by mehertz** [comment] 2023-04-25 16:56
Could you share your code? We've not seen this before.

**Comment by qc00** [comment] 2023-04-25 20:37
I have only seen this kind of issues under Windows because the old default map size setting in LMDB is too small.

Could you confirm which build and OS you're using?

**Comment by jjerphan** [comment] 2023-06-08 09:08
Hi @Tianxu-Jia,

Thank you for this report. Could you [craft a minimal reproducer](https://matthewrocklin.com/minimal-bug-reports) for the behavior you report?

If your report appears to be dependent on external data files and cannot be reproduced without them, please describe your data files in as much detail as you can.

Also, if the code is too long, feel free to put it in a [public gist](https://gist.github.com/) and link it in this issue.

We acknowledge that this requires some effort from you, but it really helps us locate the problem and we thank you for helping us out.

**Comment by poodlewars** [comment] 2023-07-14 11:27
I'm going to assume that this is similar to issue #520 which had similar symptoms and close this issue. A fix for it is currently in PR.

**Closed by poodlewars** 2023-07-14 11:27 UTC
Labels: bug
