### ISSUE TITLE
Match Pandas default `NaN` handling in aggregations

### ISSUE THREAD

**Issue by alexowens90** [man-group/ArcticDB#958] opened 2023-10-13 10:00 UTC
Min and max already (correctly) ignore NaNs when aggregating.
However, sum and mean will currently return NaN for any group that contains a NaN, which is less useful default behaviour than ignoring these values during the aggregation stage.

**Comment by DrNickClarke** [comment] 2023-12-14 14:32
This is a duplicate of https://github.com/man-group/ArcticDB/issues/935
(which has testing code included)

**Comment by poodlewars** [comment] 2023-12-19 10:30
Closing as dupe

**Closed by poodlewars** 2023-12-19 10:30 UTC
Labels: bug
