### ISSUE TITLE
Staged option for write_batch is not working

### ISSUE THREAD

**Issue by GemDot** [man-group/ArcticDB#568] opened 2023-07-07 15:10 UTC
### Describe the bug

Currently, if the staged option is set to true in the write_batch method, it has the same effect as if the option were set to false, meaning that no staging is applied. This behavior may need to be reviewed or updated to ensure that the staged option functions as intended.

### Steps/Code to Reproduce

    lib = library_factory(LibraryOptions(rows_per_segment=10))
    assert lib._nvs._lib_cfg.lib_desc.version.write_options.segment_row_size == 10
    num_columns = 16
    num_days = 200
    num_symbols = 1
    dt = datetime(2019, 4, 8, 0, 0, 0)
    column_length = 6
    num_rows_per_day = 1
    list_requests = []
    list_dataframes = {}
    for sym in range(num_symbols):
        columns = random_strings_of_length(num_columns, column_length, True)
        df = generate_dataframe(random.sample(columns, 6), dt, num_days, num_rows_per_day)
        list_requests.append(WritePayload("symbol_" + str(sym), df, metadata="great_metadata" + str(sym)))
        list_dataframes[sym] = df

    batch = lib.write_batch(list_requests, staged = True)

#Therefore, the following code will have no effect, although it was intended to perform compaction on the incomplete
```
    for sym in range(num_symbols):
        lmdb_version_store_big_map.version_store.compact_incomplete("symbol_"+str(sym), False, False)
```

### Expected Results

The performance of the staged write is higher. So we expect those writes to be faster.

### OS, Python Version and ArcticDB Version

Python: 3.6.8 (default, Nov 16 2020, 16:55:22) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-44)]
OS: Linux-5.15.0-72-generic-x86_64-with-centos-7.9.2009-Core
Traceback (most recent call last):
  File "<string>", line 1, in <module>

**Comment by jamesmunro** [comment] 2023-08-17 14:58
@GemDot This looks like a duplicate of #554.  Closing.  Please re-open if I'm wrong.

**Closed by jamesmunro** 2023-08-17 14:58 UTC
Labels: bug
