### ISSUE TITLE
Does lmdb support read-only mode?

### ISSUE THREAD

**Issue by inie0722** [man-group/ArcticDB#1216] opened 2024-01-09 10:05 UTC

**Comment by IvoDD** [comment] 2024-01-12 15:01
We currently don't expose a way to open an Arctic client in read-only mode. 

We're already planning to expose an API in the arctic client to do this: https://github.com/man-group/ArcticDB/issues/1124

Closing as duplicate of https://github.com/man-group/ArcticDB/issues/1124

**Closed by IvoDD** 2024-01-12 15:01 UTC
