### ISSUE TITLE
Cannot install to via miniforge on M1 Mac

### ISSUE THREAD

**Issue by this-josh** [man-group/ArcticDB#611] opened 2023-07-18 10:34 UTC
### Describe the bug

I am having trouble getting ArcticDB to run on my M1 mac. I appreciate there are issues releasing it via PyPi, but I also cannot see how to [build it myself](https://github.com/man-group/ArcticDB/blob/master/docs/mkdocs/docs/technical/contributing.md) so I can avoid conda (my preference). Given this I have installed conda via `brew install --cask miniforge`.

There seems to be some architecture issue `(have 'x86_64', need 'arm64')`, I am reasonably confident my Python version is arm, see relevant box below.

### Steps/Code to Reproduce

```zsh
>>> conda config --env --set subdir osx-arm64 # ensure arm is used, have tried without this
>>> conda create -n del python=3.11 -y
>>> conda activate del
>>> conda install -c conda-forge arcticdb -y
Collecting package metadata (current_repodata.json): done
Solving environment: unsuccessful initial attempt using frozen solve. Retrying with flexible solve.
Solving environment: unsuccessful attempt using repodata from current_repodata.json, retrying with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /opt/homebrew/Caskroom/miniforge/base/envs/del

  added / updated specs:
    - arcticdb


The following NEW packages will be INSTALLED:

  arcticdb           conda-forge/osx-arm64::arcticdb-1.5.0-py311h3ed4776_0
  attrs              conda-forge/noarch::attrs-23.1.0-pyh71513ae_1
  aws-c-auth         conda-forge/osx-arm64::aws-c-auth-0.7.0-hf4e22b4_2
  aws-c-cal          conda-forge/osx-arm64::aws-c-cal-0.6.0-h43a37b4_0
  aws-c-common       conda-forge/osx-arm64::aws-c-common-0.8.23-hb547adb_0
  aws-c-compression  conda-forge/osx-arm64::aws-c-compression-0.2.17-h31a6291_1
  aws-c-event-stream conda-forge/osx-arm64::aws-c-event-stream-0.3.1-h1e1aaf7_1
  aws-c-http         conda-forge/osx-arm64::aws-c-http-0.7.11-h3107daf_0
  aws-c-io           conda-forge/osx-arm64::aws-c-io-0.13.28-hf096fb3_0
  aws-c-mqtt         conda-forge/osx-arm64::aws-c-mqtt-0.8.14-h9418dbe_2
  aws-c-s3           conda-forge/osx-arm64::aws-c-s3-0.3.13-h79b0d72_2
  aws-c-sdkutils     conda-forge/osx-arm64::aws-c-sdkutils-0.1.11-h31a6291_1
  aws-checksums      conda-forge/osx-arm64::aws-checksums-0.1.16-h31a6291_1
  aws-crt-cpp        conda-forge/osx-arm64::aws-crt-cpp-0.20.3-h0918d87_4
  aws-sdk-cpp        conda-forge/osx-arm64::aws-sdk-cpp-1.10.57-h6f3a27c_17
  boost-cpp          conda-forge/osx-arm64::boost-cpp-1.78.0-h9ed8d21_3
  c-ares             conda-forge/osx-arm64::c-ares-1.19.1-hb547adb_0
  cyrus-sasl         conda-forge/osx-arm64::cyrus-sasl-2.1.27-h59bf3fd_6
  dataclasses        conda-forge/noarch::dataclasses-0.8-pyhc8e2a94_3
  decorator          conda-forge/noarch::decorator-5.1.1-pyhd8ed1ab_0
  double-conversion  conda-forge/osx-arm64::double-conversion-3.3.0-h13dd4ca_0
  fmt                conda-forge/osx-arm64::fmt-9.1.0-hffc8910_0
  folly              conda-forge/osx-arm64::folly-2023.07.17.00-h1e8fca9_0
  gflags             conda-forge/osx-arm64::gflags-2.2.2-hc88da5d_1004
  glog               conda-forge/osx-arm64::glog-0.6.0-h6da1cb0_0
  grpcio             conda-forge/osx-arm64::grpcio-1.54.2-py311ha891d26_2
  grpcio-tools       conda-forge/osx-arm64::grpcio-tools-1.54.2-py311ha891d26_1
  icu                conda-forge/osx-arm64::icu-72.1-he12128b_0
  krb5               conda-forge/osx-arm64::krb5-1.20.1-h69eda48_0
  libabseil          conda-forge/osx-arm64::libabseil-20230125.3-cxx17_h13dd4ca_0
  libblas            conda-forge/osx-arm64::libblas-3.9.0-17_osxarm64_openblas
  libbson            conda-forge/osx-arm64::libbson-1.23.2-hb7217d7_0
  libcblas           conda-forge/osx-arm64::libcblas-3.9.0-17_osxarm64_openblas
  libcurl            conda-forge/osx-arm64::libcurl-8.1.2-h912dcd9_0
  libcxx             conda-forge/osx-arm64::libcxx-16.0.6-h4653b0c_0
  libedit            conda-forge/osx-arm64::libedit-3.1.20191231-hc8eb9b7_2
  libev              conda-forge/osx-arm64::libev-4.33-h642e427_1
  libevent           conda-forge/osx-arm64::libevent-2.1.12-h2757513_1
  libgfortran        conda-forge/osx-arm64::libgfortran-5.0.0-12_2_0_hd922786_31
  libgfortran5       conda-forge/osx-arm64::libgfortran5-12.2.0-h0eea778_31
  libgrpc            conda-forge/osx-arm64::libgrpc-1.54.2-h0a338ca_2
  liblapack          conda-forge/osx-arm64::liblapack-3.9.0-17_osxarm64_openblas
  libmongoc          conda-forge/osx-arm64::libmongoc-1.23.2-hfc821f9_0
  libmongocxx        conda-forge/osx-arm64::libmongocxx-3.7.2-habc69d2_0
  libnghttp2         conda-forge/osx-arm64::libnghttp2-1.52.0-hae82a92_0
  libntlm            conda-forge/osx-arm64::libntlm-1.4-h3422bc3_1002
  libopenblas        conda-forge/osx-arm64::libopenblas-0.3.23-openmp_hc731615_0
  libprotobuf        conda-forge/osx-arm64::libprotobuf-3.21.12-hb5ab8b9_0
  libsodium          conda-forge/osx-arm64::libsodium-1.0.18-h27ca646_1
  libssh2            conda-forge/osx-arm64::libssh2-1.11.0-h7a5bd25_0
  llvm-openmp        conda-forge/osx-arm64::llvm-openmp-16.0.6-h1c12783_0
  lmdb               conda-forge/osx-arm64::lmdb-0.9.22-hb547adb_0
  lz4-c              conda-forge/osx-arm64::lz4-c-1.9.4-hb7217d7_0
  msgpack-c          conda-forge/osx-arm64::msgpack-c-6.0.0-ha614eb4_0
  msgpack-python     conda-forge/osx-arm64::msgpack-python-1.0.5-py311hd6ee22a_0
  numpy              conda-forge/osx-arm64::numpy-1.25.1-py311hb8f3215_0
  pandas             conda-forge/osx-arm64::pandas-1.5.3-py311h4eec4a9_1
  pcre               conda-forge/osx-arm64::pcre-8.45-hbdafb3b_0
  prometheus-cpp     conda-forge/osx-arm64::prometheus-cpp-1.1.0-hcd26875_1
  prometheus_client  conda-forge/noarch::prometheus_client-0.17.1-pyhd8ed1ab_0
  protobuf           conda-forge/osx-arm64::protobuf-4.21.12-py311ha397e9f_0
  psutil             conda-forge/osx-arm64::psutil-5.9.5-py311he2be06e_0
  python-dateutil    conda-forge/noarch::python-dateutil-2.8.2-pyhd8ed1ab_0
  python-xxhash      conda-forge/osx-arm64::python-xxhash-3.2.0-py311he2be06e_0
  python_abi         conda-forge/osx-arm64::python_abi-3.11-3_cp311
  pytz               conda-forge/noarch::pytz-2023.3-pyhd8ed1ab_0
  pyyaml             conda-forge/osx-arm64::pyyaml-6.0-py311he2be06e_5
  re2                conda-forge/osx-arm64::re2-2023.03.02-hc5e2d97_0
  six                conda-forge/noarch::six-1.16.0-pyh6c4a22f_0
  snappy             conda-forge/osx-arm64::snappy-1.1.10-h17c5cce_0
  spdlog             conda-forge/osx-arm64::spdlog-1.11.0-h6981a3a_1
  xxhash             conda-forge/osx-arm64::xxhash-0.8.1-h1a8c8d9_0
  yaml               conda-forge/osx-arm64::yaml-0.2.5-h3422bc3_2
  zlib               conda-forge/osx-arm64::zlib-1.2.13-h53f4e23_5
  zstd               conda-forge/osx-arm64::zstd-1.5.2-h4f39d0f_7



Downloading and Extracting Packages

Preparing transaction: done
Verifying transaction: /
SafetyError: The package for numpy located at /opt/homebrew/Caskroom/miniforge/base/pkgs/numpy-1.25.1-py311hb8f3215_0
appears to be corrupted. The path 'lib/python3.11/site-packages/numpy-1.25.1.dist-info/INSTALLER'
has an incorrect size.
  reported size: 5 bytes
  actual size: 12 bytes

SafetyError: The package for numpy located at /opt/homebrew/Caskroom/miniforge/base/pkgs/numpy-1.25.1-py311hb8f3215_0
appears to be corrupted. The path 'lib/python3.11/site-packages/numpy-1.25.1.dist-info/LICENSE.txt'
has an incorrect size.
  reported size: 2179 bytes
  actual size: 81313 bytes

SafetyError: The package for numpy located at /opt/homebrew/Caskroom/miniforge/base/pkgs/numpy-1.25.1-py311hb8f3215_0
appears to be corrupted. The path 'lib/python3.11/site-packages/numpy-1.25.1.dist-info/METADATA'
has an incorrect size.
  reported size: 5545 bytes
  actual size: 5580 bytes

SafetyError: The package for numpy located at /opt/homebrew/Caskroom/miniforge/base/pkgs/numpy-1.25.1-py311hb8f3215_0
appears to be corrupted. The path 'lib/python3.11/site-packages/numpy-1.25.1.dist-info/RECORD'
has an incorrect size.
  reported size: 111597 bytes
  actual size: 81597 bytes


done
Executing transaction: done
```

```python
>>> from arcticdb import Arctic
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/homebrew/Caskroom/miniforge/base/envs/del/lib/python3.11/site-packages/arcticdb/__init__.py", line 1, in <module>
    import arcticdb_ext as _ext
ImportError: dlopen(/opt/homebrew/Caskroom/miniforge/base/envs/del/lib/python3.11/site-packages/arcticdb_ext.cpython-311-darwin.so, 0x0002): tried: '/opt/homebrew/Caskroom/miniforge/base/envs/del/lib/python3.11/site-packages/arcticdb_ext.cpython-311-darwin.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/Caskroom/miniforge/base/envs/del/lib/python3.11/site-packages/arcticdb_ext.cpython-311-darwin.so' (no such file), '/opt/homebrew/Caskroom/miniforge/base/envs/del/lib/python3.11/site-packages/arcticdb_ext.cpython-311-darwin.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64'))
```

### Expected Results

No error thrown. 

### OS, Python Version and ArcticDB Version

```
Python: 3.11.4 | packaged by conda-forge | (main, Jun 10 2023, 18:08:41) [Clang 15.0.7 ]
OS: macOS-13.4.1-arm64-arm-64bit
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/opt/homebrew/Caskroom/miniforge/base/envs/del/lib/python3.11/site-packages/arcticdb/__init__.py", line 1, in <module>
    import arcticdb_ext as _ext
ImportError: dlopen(/opt/homebrew/Caskroom/miniforge/base/envs/del/lib/python3.11/site-packages/arcticdb_ext.cpython-311-darwin.so, 0x0002): tried: '/opt/homebrew/Caskroom/miniforge/base/envs/del/lib/python3.11/site-packages/arcticdb_ext.cpython-311-darwin.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/Caskroom/miniforge/base/envs/del/lib/python3.11/site-packages/arcticdb_ext.cpython-311-darwin.so' (no such file), '/opt/homebrew/Caskroom/miniforge/base/envs/del/lib/python3.11/site-packages/arcticdb_ext.cpython-311-darwin.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64'))
```

### Backend storage used

NA

**Comment by this-josh** [comment] 2023-07-18 10:48
In case it is of further assistance I recreated the `del` environment after running `conda clean -a`, it gives the same error message. Now installing looks like:
```zsh
(del) ➜  ~ conda install -c conda-forge arcticdb --force-reinstall -y                                                                                                                              [18/Jul/23 | 11:41]
Collecting package metadata (current_repodata.json): done
Solving environment: unsuccessful initial attempt using frozen solve. Retrying with flexible solve.
Solving environment: unsuccessful attempt using repodata from current_repodata.json, retrying with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /opt/homebrew/Caskroom/miniforge/base/envs/del

  added / updated specs:
    - arcticdb


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    arcticdb-1.5.0             |  py311h3ed4776_0         6.2 MB  conda-forge
    aws-c-auth-0.7.0           |       hf4e22b4_2          90 KB  conda-forge
    aws-c-event-stream-0.3.1   |       h1e1aaf7_1          47 KB  conda-forge
    aws-c-http-0.7.11          |       h3107daf_0         154 KB  conda-forge
    aws-c-io-0.13.28           |       hf096fb3_0         137 KB  conda-forge
    aws-c-mqtt-0.8.14          |       h9418dbe_2         113 KB  conda-forge
    aws-c-s3-0.3.13            |       h79b0d72_2          77 KB  conda-forge
    aws-crt-cpp-0.20.3         |       h0918d87_4         216 KB  conda-forge
    aws-sdk-cpp-1.10.57        |      h6f3a27c_17         3.2 MB  conda-forge
    folly-2023.07.17.00        |       h1e8fca9_0         2.5 MB  conda-forge
    grpcio-1.54.2              |  py311ha891d26_2         714 KB  conda-forge
    grpcio-tools-1.54.2        |  py311ha891d26_1         1.3 MB  conda-forge
    libblas-3.9.0              |17_osxarm64_openblas          14 KB  conda-forge
    libcblas-3.9.0             |17_osxarm64_openblas          14 KB  conda-forge
    libgfortran-5.0.0          |12_2_0_hd922786_31         157 KB  conda-forge
    liblapack-3.9.0            |17_osxarm64_openblas          14 KB  conda-forge
    msgpack-python-1.0.5       |  py311hd6ee22a_0          81 KB  conda-forge
    numpy-1.25.1               |  py311hb8f3215_0         6.5 MB  conda-forge
    pandas-1.5.3               |  py311h4eec4a9_1        13.2 MB  conda-forge
    prometheus_client-0.17.1   |     pyhd8ed1ab_0          52 KB  conda-forge
    protobuf-4.21.12           |  py311ha397e9f_0         342 KB  conda-forge
    psutil-5.9.5               |  py311he2be06e_0         495 KB  conda-forge
    python-xxhash-3.2.0        |  py311he2be06e_0          20 KB  conda-forge
    python_abi-3.11            |          3_cp311           6 KB  conda-forge
    pyyaml-6.0                 |  py311he2be06e_5         189 KB  conda-forge
    zstd-1.5.2                 |       h4f39d0f_7         310 KB  conda-forge
    ------------------------------------------------------------
                                           Total:        36.0 MB

The following NEW packages will be INSTALLED:

  arcticdb           conda-forge/osx-arm64::arcticdb-1.5.0-py311h3ed4776_0
  attrs              conda-forge/noarch::attrs-23.1.0-pyh71513ae_1
  aws-c-auth         conda-forge/osx-arm64::aws-c-auth-0.7.0-hf4e22b4_2
  aws-c-cal          conda-forge/osx-arm64::aws-c-cal-0.6.0-h43a37b4_0
  aws-c-common       conda-forge/osx-arm64::aws-c-common-0.8.23-hb547adb_0
  aws-c-compression  conda-forge/osx-arm64::aws-c-compression-0.2.17-h31a6291_1
  aws-c-event-stream conda-forge/osx-arm64::aws-c-event-stream-0.3.1-h1e1aaf7_1
  aws-c-http         conda-forge/osx-arm64::aws-c-http-0.7.11-h3107daf_0
  aws-c-io           conda-forge/osx-arm64::aws-c-io-0.13.28-hf096fb3_0
  aws-c-mqtt         conda-forge/osx-arm64::aws-c-mqtt-0.8.14-h9418dbe_2
  aws-c-s3           conda-forge/osx-arm64::aws-c-s3-0.3.13-h79b0d72_2
  aws-c-sdkutils     conda-forge/osx-arm64::aws-c-sdkutils-0.1.11-h31a6291_1
  aws-checksums      conda-forge/osx-arm64::aws-checksums-0.1.16-h31a6291_1
  aws-crt-cpp        conda-forge/osx-arm64::aws-crt-cpp-0.20.3-h0918d87_4
  aws-sdk-cpp        conda-forge/osx-arm64::aws-sdk-cpp-1.10.57-h6f3a27c_17
  boost-cpp          conda-forge/osx-arm64::boost-cpp-1.78.0-h9ed8d21_3
  c-ares             conda-forge/osx-arm64::c-ares-1.19.1-hb547adb_0
  cyrus-sasl         conda-forge/osx-arm64::cyrus-sasl-2.1.27-h59bf3fd_6
  dataclasses        conda-forge/noarch::dataclasses-0.8-pyhc8e2a94_3
  decorator          conda-forge/noarch::decorator-5.1.1-pyhd8ed1ab_0
  double-conversion  conda-forge/osx-arm64::double-conversion-3.3.0-h13dd4ca_0
  fmt                conda-forge/osx-arm64::fmt-9.1.0-hffc8910_0
  folly              conda-forge/osx-arm64::folly-2023.07.17.00-h1e8fca9_0
  gflags             conda-forge/osx-arm64::gflags-2.2.2-hc88da5d_1004
  glog               conda-forge/osx-arm64::glog-0.6.0-h6da1cb0_0
  grpcio             conda-forge/osx-arm64::grpcio-1.54.2-py311ha891d26_2
  grpcio-tools       conda-forge/osx-arm64::grpcio-tools-1.54.2-py311ha891d26_1
  icu                conda-forge/osx-arm64::icu-72.1-he12128b_0
  krb5               conda-forge/osx-arm64::krb5-1.20.1-h69eda48_0
  libabseil          conda-forge/osx-arm64::libabseil-20230125.3-cxx17_h13dd4ca_0
  libblas            conda-forge/osx-arm64::libblas-3.9.0-17_osxarm64_openblas
  libbson            conda-forge/osx-arm64::libbson-1.23.2-hb7217d7_0
  libcblas           conda-forge/osx-arm64::libcblas-3.9.0-17_osxarm64_openblas
  libcurl            conda-forge/osx-arm64::libcurl-8.1.2-h912dcd9_0
  libcxx             conda-forge/osx-arm64::libcxx-16.0.6-h4653b0c_0
  libedit            conda-forge/osx-arm64::libedit-3.1.20191231-hc8eb9b7_2
  libev              conda-forge/osx-arm64::libev-4.33-h642e427_1
  libevent           conda-forge/osx-arm64::libevent-2.1.12-h2757513_1
  libgfortran        conda-forge/osx-arm64::libgfortran-5.0.0-12_2_0_hd922786_31
  libgfortran5       conda-forge/osx-arm64::libgfortran5-12.2.0-h0eea778_31
  libgrpc            conda-forge/osx-arm64::libgrpc-1.54.2-h0a338ca_2
  liblapack          conda-forge/osx-arm64::liblapack-3.9.0-17_osxarm64_openblas
  libmongoc          conda-forge/osx-arm64::libmongoc-1.23.2-hfc821f9_0
  libmongocxx        conda-forge/osx-arm64::libmongocxx-3.7.2-habc69d2_0
  libnghttp2         conda-forge/osx-arm64::libnghttp2-1.52.0-hae82a92_0
  libntlm            conda-forge/osx-arm64::libntlm-1.4-h3422bc3_1002
  libopenblas        conda-forge/osx-arm64::libopenblas-0.3.23-openmp_hc731615_0
  libprotobuf        conda-forge/osx-arm64::libprotobuf-3.21.12-hb5ab8b9_0
  libsodium          conda-forge/osx-arm64::libsodium-1.0.18-h27ca646_1
  libssh2            conda-forge/osx-arm64::libssh2-1.11.0-h7a5bd25_0
  llvm-openmp        conda-forge/osx-arm64::llvm-openmp-16.0.6-h1c12783_0
  lmdb               conda-forge/osx-arm64::lmdb-0.9.22-hb547adb_0
  lz4-c              conda-forge/osx-arm64::lz4-c-1.9.4-hb7217d7_0
  msgpack-c          conda-forge/osx-arm64::msgpack-c-6.0.0-ha614eb4_0
  msgpack-python     conda-forge/osx-arm64::msgpack-python-1.0.5-py311hd6ee22a_0
  numpy              conda-forge/osx-arm64::numpy-1.25.1-py311hb8f3215_0
  pandas             conda-forge/osx-arm64::pandas-1.5.3-py311h4eec4a9_1
  pcre               conda-forge/osx-arm64::pcre-8.45-hbdafb3b_0
  prometheus-cpp     conda-forge/osx-arm64::prometheus-cpp-1.1.0-hcd26875_1
  prometheus_client  conda-forge/noarch::prometheus_client-0.17.1-pyhd8ed1ab_0
  protobuf           conda-forge/osx-arm64::protobuf-4.21.12-py311ha397e9f_0
  psutil             conda-forge/osx-arm64::psutil-5.9.5-py311he2be06e_0
  python-dateutil    conda-forge/noarch::python-dateutil-2.8.2-pyhd8ed1ab_0
  python-xxhash      conda-forge/osx-arm64::python-xxhash-3.2.0-py311he2be06e_0
  python_abi         conda-forge/osx-arm64::python_abi-3.11-3_cp311
  pytz               conda-forge/noarch::pytz-2023.3-pyhd8ed1ab_0
  pyyaml             conda-forge/osx-arm64::pyyaml-6.0-py311he2be06e_5
  re2                conda-forge/osx-arm64::re2-2023.03.02-hc5e2d97_0
  six                conda-forge/noarch::six-1.16.0-pyh6c4a22f_0
  snappy             conda-forge/osx-arm64::snappy-1.1.10-h17c5cce_0
  spdlog             conda-forge/osx-arm64::spdlog-1.11.0-h6981a3a_1
  xxhash             conda-forge/osx-arm64::xxhash-0.8.1-h1a8c8d9_0
  yaml               conda-forge/osx-arm64::yaml-0.2.5-h3422bc3_2
  zlib               conda-forge/osx-arm64::zlib-1.2.13-h53f4e23_5
  zstd               conda-forge/osx-arm64::zstd-1.5.2-h4f39d0f_7



Downloading and Extracting Packages

Preparing transaction: done
Verifying transaction: done
Executing transaction: done
```

Trying to import arctic gives the same error
```python
>>> from arcticdb import Arctic
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/homebrew/Caskroom/miniforge/base/envs/del/lib/python3.11/site-packages/arcticdb/__init__.py", line 1, in <module>
    import arcticdb_ext as _ext
ImportError: dlopen(/opt/homebrew/Caskroom/miniforge/base/envs/del/lib/python3.11/site-packages/arcticdb_ext.cpython-311-darwin.so, 0x0002): tried: '/opt/homebrew/Caskroom/miniforge/base/envs/del/lib/python3.11/site-packages/arcticdb_ext.cpython-311-darwin.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/Caskroom/miniforge/base/envs/del/lib/python3.11/site-packages/arcticdb_ext.cpython-311-darwin.so' (no such file), '/opt/homebrew/Caskroom/miniforge/base/envs/del/lib/python3.11/site-packages/arcticdb_ext.cpython-311-darwin.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64'))

**Comment by qc00** [comment] 2023-07-18 12:51
This has been reported in [another issue](https://github.com/man-group/ArcticDB/issues/458#issuecomment-1632420466). I believe @DerThorsten is looking at it?

**Comment by jamesmunro** [comment] 2023-07-19 16:58
@this-josh Closing as we believe this is a duplicate of #458

**Closed by jamesmunro** 2023-07-19 16:58 UTC
Labels: bug
